### ISSUE TITLE
Missing argument for parameter #1 in call

### ISSUE THREAD

**Issue by passatgt** [loicgriffie/Alerts-Pickers#4]
Hi!

I installed it as a pod, imported RLBAlertsPickers in my view controller but when i try to show an alert:

`alert.show()`

I got this: 

`Missing argument for parameter #1 in call`

Any ideas what might be the issue? Seems like the show function is not extended. But the alert init with UIAlertController works fine...

Thanks

**Comment by loicgriffie** [comment]
@passatgt @simformsolutions I'm on it. I shall deliver update in next couple of hours

**Comment by loicgriffie** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  RLBAlertsPickers (1.1.1) successfully published
 📅  January 3rd, 15:13
 🌎  https://cocoapods.org/pods/RLBAlertsPickers
 👍  Tell your friends!
--------------------------------------------------------------------------------
