### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by Lazza** [loicgriffie/Alerts-Pickers#7]
Could you consider adding support for installing this as a Carthage framework?

Thank you!

**Comment by riki-dexter** [comment]
Can you tell me how to add this library with Carthage?
With `github "loicgriffie/Alerts-Pickers"` i get this error: `Dependency Alerts-Pickers has no shared framework schemes for any of the platforms: iOS If you believe this to be an error, please file an issue with the maintainers at https://github.com/loicgriffie/Alerts-Pickers/issues/new`

Thank you

**Comment by Lazza** [comment]
Maybe try with a specific commit?

    github "loicgriffie/Alerts-Pickers" "5ce7637f4c8d5118442f1a9ae781020fa80fccb9"

But it _should_ work with `master`, as well.
